language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
notifications:
  email: false
before_script:
  - composer self-update
  - COMPOSER=composer.travis.json composer install
  - bower install
  - mysql -u root < test/build/create-user.sql
  - export PATH=`pwd`/bin:$PATH
  - cp config/env-config.php.example config/env-config.php
  - touch /tmp/phantom-awooga.log
  - rm -f /tmp/awooga-screenshot-data.log
script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - cat /tmp/phantom-awooga.log
  - cat /tmp/awooga-screenshot-data.log
