language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
notifications:
  email: false
before_script:
  - composer self-update
  - COMPOSER=composer.travis.json composer install
  - git submodule init
  - git submodule update
  - npm install bower
  - bower install
  - mysql -u root < test/build/create-user.sql
  - export PATH=`pwd`/bin:$PATH
  - cp config/env-config.php.example config/env-config.php
  - touch /tmp/phantom-awooga.log
  - which phpunit
  - which phantomjs
script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - cat /tmp/phantom-awooga.log
