language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
notifications:
  email: false
before_script:
  - composer self-update
  - composer install
  - mysql -u root < test/build/create-user.sql
  - export PATH=`pwd`/bin:$PATH
